service:
  name: alertCenter

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-north-1'}
  stackName: alertcenter
  apiName: alertcenter
  deploymentBucket:
    name: name.jhie.${self:provider.region}.serverless.deploys
    serverSideEncryption: AES256
  apiKeys:
    - ruuvibridge
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: jhie.name
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
