service:
  name: alertCenter

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'eu-north-1'}
  stackName: alertcenter
  apiName: alertcenter
  deploymentBucket:
    name: name.jhie.${self:provider.region}.serverless.deploys
    serverSideEncryption: AES256
  apiKeys:
    - ruuvibridge
  apiGateway:
    apiKeySourceType: HEADER
    minimumCompressionSize: 1024
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "*"

functions:
  motion:
    handler: handler.sensor_motion
    events:
      - http:
          path: motion
          method: post
          private: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: jhie.name
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

resources:
  Description: Dynamo table for storing motion events
  Resources:
    MotionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: motion
        AttributeDefinitions:
          - AttributeName: Tag
            AttributeType: S
          - AttributeName: EventTime
            AttributeType: N
        KeySchema:
          - AttributeName: Tag
            KeyType: HASH
          - AttributeName: EventTime
            KeyType: RANGE
        SSESpecification:
          SSEEnabled: true
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: Expires
          Enabled: true
